Update README.md to reference Remote Asset API in additon to REAPI
bazelbuild/remote-apis pull request #218
Opened 2022-04-12 21:34 UTC by jeremiahbonney

When looking for a brief description of the Remote Asset API, I realized that it was only discoverable by traversing the repo and mentioned anywhere. This PR reworks the intro to the `README.md` a bit to add a link and simple description of the Remote Asset API to make it more discoverable.

Happy to rework the description or do something like have a dedicated section for the other APIs in this repo that aren't the REAPI, let me know what y'all think!

2022-04-13 21:22 UTC, bergsieker approved these changes

2022-04-13 21:25 UTC, bergsieker requested changes
Actually, we should probably also include the logstream API here, too. Maybe an intro paragraph tying all of these together as "things related to remote execution" and then a paragraph/bullet for each API?

2022-04-19 01:16 UTC, EdSchouten approved these changes

2022-04-26 14:55 UTC, sstriker approved these changes

2022-04-26 14:57 UTC, sstriker commented
> Actually, we should probably also include the logstream API here, too. Maybe an intro paragraph tying all of these together as "things related to remote execution" and then a paragraph/bullet for each API?

@bergsieker I believe this is now done and should resolve your request for changes :-)

2022-04-27 17:59 UTC, merged