Add buck2 to the list of clients.
bazelbuild/remote-apis pull request #254
Opened 2023-05-22 14:37 UTC by sluongng

It's tested against different implementations of Remote APIs
https://buck2.build/docs/remote_execution/.

2023-05-22 15:28 UTC, EdSchouten requested changes

2023-05-22 15:28 UTC, EdSchouten commented on README.md
> +* [Buck2](https://github.com/facebook/buck2)
Could we please keep this list sorted?

2023-05-24 13:02 UTC, EdSchouten approved these changes

2023-05-24 17:07 UTC, brentleyjones approved these changes

2023-05-24 18:36 UTC, merged