publish-to-BCR setup
bazelbuild/remote-apis pull request #313
Opened 2024-10-01 22:54 UTC by Wyverald

@bergsieker: I volunteered you to be a module maintainer :) it should be very low maintenance, but let me know if you would rather not.

We can cut a release after this gets merged and watch it show up in BCR. (Note that we'll need to attach a release archive -- I can do this part.)

2024-10-03 13:40 UTC, bergsieker requested changes

2024-10-03 13:40 UTC, bergsieker commented on .bcr/metadata.template.json
> +      "github": "berksieker",
s/bergksieker/bergsieker/

2024-10-03 13:40 UTC, bergsieker commented on .bcr/metadata.template.json
> +      "name": "Steven Bergsieker"
Should you add bergsieker@google.com as an email contact?

2024-10-03 13:40 UTC, bergsieker commented on .bcr/config.yml
Where can I find the expected format and information for these files?

2024-10-03 20:38 UTC, Wyverald commented on .bcr/config.yml
https://github.com/bazel-contrib/publish-to-bcr/tree/main/templates

2024-10-15 16:10 UTC, bentekkie commented
> hmm, maybe this is a good opportunity to actually split this module into several ones (one per language). For example, Bazel's own use of remote-apis requires the Java gRPC targets, which aren't currently in this repo. I'll probably send another change tomorrow.

Can this be done orthogonally to getting this into bcr? Reclient and remote-apis-sdks's usage of this module would be greatly simplified if we can get this deployed to bcr.

2024-11-13 14:46 UTC, bergsieker commented
@Wyverald can we pick this up again?

2024-11-13 21:59 UTC, Wyverald commented
Sorry, I've been busy with managing Bazel's 8.0 release. Are you blocked on this change? I think you mentioned a few action items from your side in a previous email thread (including setting a new release schedule, etc). Are those completed already?

2025-01-09 21:11 UTC, bergsieker commented
> Sorry, I've been busy with managing Bazel's 8.0 release. Are you blocked on this change? I think you mentioned a few action items from your side in a previous email thread (including setting a new release schedule, etc). Are those completed already?

We've agreed to move to a monthly release model, skipping months where there are no (meaningful) commits). We're also moving to date-based versioning. Ideally we'll cut the first such release around next Tuesday. Is it better to get this in place before that release, or do we need to wait for that release and use it as a baseline for the first BCR release the following month?

2026-03-13 20:54 UTC, mbland commented
FYI, just opened #370 to pick this up, with @Wyverald's blessing.

2026-03-18 20:11 UTC, closed without merging